### ISSUE TITLE
Hexo client 打开失败

### ISSUE THREAD

**Issue by silly-Richard** [gaoyoubo/hexo-client#102]
TypeError: Cannot read property 'enable' of undefined
    at D:\hexo\blog\themes\hexo-theme-next\scripts\filters\comment\changyan.js:11:23
    at a.execSync (app://./js/chunk-vendors.6411eb4f.js:260:97160)
    at F.execFilterSync (app://./js/chunk-vendors.6411eb4f.js:474:7524)
    at module.exports (D:\hexo\blog\themes\hexo-theme-next\scripts\events\lib\injects.js:58:8)
    at F.<anonymous> (D:\hexo\blog\themes\hexo-theme-next\scripts\events\index.js:9:27)
    at F.emit (events.js:200:13)
    at F._generate (app://./js/chunk-vendors.6411eb4f.js:474:5810)
    at app://./js/chunk-vendors.6411eb4f.js:474:5180
    at c (app://./js/chunk-vendors.6411eb4f.js:486:131309)
    at I._settlePromiseFromHandler (app://./js/chunk-vendors.6411eb4f.js:486:103919)
    at I._settlePromise (app://./js/chunk-vendors.6411eb4f.js:486:104724)
    at I._settlePromise0 (app://./js/chunk-vendors.6411eb4f.js:486:105426)
    at I._settlePromises (app://./js/chunk-vendors.6411eb4f.js:486:106780)
    at I._fulfill (app://./js/chunk-vendors.6411eb4f.js:486:105797)
    at c._resolve (app://./js/chunk-vendors.6411eb4f.js:486:110418)
    at c._promiseFulfilled (app://./js/chunk-vendors.6411eb4f.js:486:110767)
    at I._settlePromise (app://./js/chunk-vendors.6411eb4f.js:486:104826)
    at I._settlePromise0 (app://./js/chunk-vendors.6411eb4f.js:486:105426)
    at I._settlePromises (app://./js/chunk-vendors.6411eb4f.js:486:106780)
    at p (app://./js/chunk-vendors.6411eb4f.js:486:57816)
    at u (app://./js/chunk-vendors.6411eb4f.js:486:57754)
    at o._drainQueues (app://./js/chunk-vendors.6411eb4f.js:486:58699)
From previous event:
    at I.q [as _captureStackTrace] (app://./js/chunk-vendors.6411eb4f.js:486:72775)
    at I._then (app://./js/chunk-vendors.6411eb4f.js:486:99299)
    at I.then (app://./js/chunk-vendors.6411eb4f.js:486:97645)
    at F.watch (app://./js/chunk-vendors.6411eb4f.js:474:5089)
    at _.init (app://./js/app.f555d8f8.js:1:7497)
    at async _.start (app://./js/app.f555d8f8.js:1:7268)
    at async o.init (app://./js/app.f555d8f8.js:1:23004)

**Comment by i207M** [comment]
+1

**Comment by zzq0324** [comment]
+1
